/**
 * Authentic High-Jewellery Catalogue with PBR Material Metadata.
 * All artificial 3D CAD/synthetic models removed in favor of authentic photographic pieces.
 */
export const ORNAMENTS = [
  {
    id: "necklace-caratlane-serenity-choker",
    name: "Serenity Gleam Diamond Choker",
    category: "necklace",
    type: "necklace",
    image: "/ornaments/necklace-caratlane-serenity-choker.png",
    metal: "14KT Yellow Gold",
    gems: "Brilliant Pavé Diamonds",
    price: "₹91,861",
    materialPreset: "diamond",
    defaultScale: 1.25,
    defaultOffsetY: -6,
    fitProfile: { anchorBlend: 0.34, widthMul: 1.08, lengthMul: 0.90, style: "choker" },
    description: "CaratLane high-jewellery choker featuring interlaced yellow gold arches studded with pavé diamonds."
  },
  {
    id: "necklace-caratlane-verona-diamond",
    name: "Verona Fine Diamond Necklace",
    category: "necklace",
    type: "necklace",
    image: "/ornaments/necklace-caratlane-verona-diamond.png",
    metal: "18KT Yellow Gold",
    gems: "VVS Solitaire Diamonds",
    price: "₹95,641",
    materialPreset: "diamond",
    defaultScale: 1.25,
    defaultOffsetY: -2,
    fitProfile: { anchorBlend: 0.44, widthMul: 1.04, lengthMul: 1.0, style: "collar" },
    description: "Architectural geometric links studded with round brilliant diamonds in solid 18KT yellow gold."
  },
  {
    id: "necklace-caratlane-ravishing-wave",
    name: "Ravishing Wave Diamond Necklace",
    category: "necklace",
    type: "necklace",
    image: "/ornaments/necklace-caratlane-ravishing-wave.png",
    metal: "14KT Yellow Gold",
    gems: "Graduated Multi-Row Diamonds",
    price: "₹2,11,016",
    materialPreset: "diamond",
    defaultScale: 1.30,
    defaultOffsetY: 0,
    fitProfile: { anchorBlend: 0.52, widthMul: 1.02, lengthMul: 1.06, style: "princess" },
    description: "Fluid wave-form diamond collar crafted with cascading brilliant diamonds draping the collarbones."
  },
  {
    id: "necklace-caratlane-gleaming-green",
    name: "Gleaming Green Gemstone Necklace",
    category: "necklace",
    type: "necklace",
    image: "/ornaments/necklace-caratlane-gleaming-green.png",
    metal: "14KT Yellow Gold",
    gems: "Octagonal Emerald & Pavé Diamonds",
    price: "₹3,51,695",
    materialPreset: "emerald",
    defaultScale: 1.30,
    defaultOffsetY: 0,
    fitProfile: { anchorBlend: 0.50, widthMul: 1.03, lengthMul: 1.04, style: "pendant" },
    description: "Spectacular royal emerald pendant necklace framed in brilliant diamonds on an articulated gold chain."
  },
  {
    id: "necklace-caratlane-moving-tassels",
    name: "Moving Tassels Rose Gold Necklace",
    category: "necklace",
    type: "necklace",
    image: "/ornaments/necklace-caratlane-moving-tassels.png",
    metal: "14KT Rose Gold",
    gems: "Brilliant Diamonds & Rose Fringe",
    price: "₹81,023",
    materialPreset: "gold",
    defaultScale: 1.22,
    defaultOffsetY: 0,
    fitProfile: { anchorBlend: 0.48, widthMul: 1.05, lengthMul: 1.02, style: "collar" },
    description: "Contemporary rose gold fringe necklace with dancing diamond tassels capturing movement."
  },
  {
    id: "necklace-caratlane-royal-gemstone",
    name: "Royal Heritage Multi-Layer Emerald",
    category: "necklace",
    type: "necklace",
    image: "/ornaments/necklace-caratlane-royal-gemstone.png",
    metal: "14KT Yellow Gold",
    gems: "Zambian Emeralds & Diamonds",
    price: "₹82,775",
    materialPreset: "emerald",
    defaultScale: 1.35,
    defaultOffsetY: 0,
    fitProfile: { anchorBlend: 0.56, widthMul: 1.0, lengthMul: 1.10, style: "layered" },
    description: "Multi-layered royal bridal necklace with cascading emerald teardrops and diamond florets."
  },
  // ── 5 GENUINE 3D PROCEDURAL & CAD PIECES ─────────────────────────
  {
    id: "3d-leaf-pendant-gold",
    name: "3D Royal Gold Leaf & Pavé Pendant",
    category: "3d",
    type: "necklace",
    is3D: true,
    model: "/models/leaf-pendant.stl",
    image: "/ornaments/necklace-3d-leaf.png",
    metal: "22K Solid Gold CAD",
    gems: "Pavé Diamonds",
    price: "₹3,40,000",
    materialPreset: "gold22k",
    defaultScale: 1.25,
    defaultOffsetY: -2,
    fitProfile: { anchorBlend: 0.46, widthMul: 1.05, lengthMul: 1.0, style: "pendant" },
    description: "Authentic 3D Rhino CAD leaf pendant with natural torque chain wrapping the neck cylinder."
  },
  {
    id: "3d-diamond-solitaire",
    name: "3D Solitaire Brilliant Diamond",
    category: "3d",
    type: "necklace",
    is3D: true,
    image: "/ornaments/necklace-diamond-solitaire.png",
    metal: "950 Platinum 3D",
    gems: "Faceted Solitaire Diamond",
    price: "₹8,50,000",
    materialPreset: "diamond",
    defaultScale: 1.25,
    defaultOffsetY: -4,
    fitProfile: { anchorBlend: 0.44, widthMul: 1.04, lengthMul: 0.98, style: "pendant" },
    description: "Faceted 3D brilliant-cut diamond encased in a 6-prong platinum crown basket with fine chain."
  },
  {
    id: "3d-emerald-octagon",
    name: "3D Colombian Emerald Octagon",
    category: "3d",
    type: "necklace",
    is3D: true,
    image: "/ornaments/necklace-caratlane-gleaming-green.png",
    metal: "18K Yellow Gold 3D",
    gems: "Faceted Zambian Emerald",
    price: "₹4,25,000",
    materialPreset: "emerald",
    defaultScale: 1.25,
    defaultOffsetY: -2,
    fitProfile: { anchorBlend: 0.46, widthMul: 1.05, lengthMul: 1.02, style: "pendant" },
    description: "Faceted octagonal emerald centerpiece in a stepped architectural 18K gold bezel."
  },
  {
    id: "3d-ruby-teardrop",
    name: "3D Crimson Pear-Cut Ruby Drop",
    category: "3d",
    type: "necklace",
    is3D: true,
    image: "/ornaments/necklace-caratlane-royal-gemstone.png",
    metal: "18K Rose Gold 3D",
    gems: "Pear Ruby & Pavé Halo",
    price: "₹5,10,000",
    materialPreset: "ruby",
    defaultScale: 1.25,
    defaultOffsetY: -2,
    fitProfile: { anchorBlend: 0.48, widthMul: 1.04, lengthMul: 1.04, style: "pendant" },
    description: "3D faceted pear-cut pigeon blood ruby surrounded by a halo of brilliant pavé diamonds."
  },
  {
    id: "3d-cuban-link-chain",
    name: "3D Solid Gold Cuban Link Choker",
    category: "3d",
    type: "necklace",
    is3D: true,
    image: "/ornaments/necklace-royal-gold.png",
    metal: "14K Yellow Gold 3D",
    gems: "Solid Interlocking Links",
    price: "₹2,80,000",
    materialPreset: "gold",
    defaultScale: 1.25,
    defaultOffsetY: -6,
    fitProfile: { anchorBlend: 0.36, widthMul: 1.08, lengthMul: 0.92, style: "choker" },
    description: "36 interlocking solid 14K gold links dynamically following cervical contours in true 3D."
  },
  {
    id: "necklace-royal-gold",
    name: "Royal Heritage Choker (Classic)",
    category: "necklace",
    type: "necklace",
    image: "/ornaments/necklace-royal-gold.png",
    metal: "22K Yellow Gold",
    gems: "Rubies & Basra Pearls",
    price: "₹3,85,000",
    materialPreset: "gold22k",
    defaultScale: 1.25,
    defaultOffsetY: -6,
    fitProfile: { anchorBlend: 0.33, widthMul: 1.09, lengthMul: 0.88, style: "choker" },
    description: "Handcrafted 22K filigree choker with cabochon rubies and cascading natural Basra pearl drops."
  },
  {
    id: "necklace-diamond-solitaire",
    name: "Elysian Diamond Rivière",
    category: "necklace",
    type: "necklace",
    image: "/ornaments/necklace-diamond-solitaire.png",
    metal: "950 Platinum",
    gems: "VVS1 Round & Emerald Diamonds",
    price: "₹9,80,000",
    materialPreset: "diamond",
    defaultScale: 1.25,
    defaultOffsetY: -2,
    fitProfile: { anchorBlend: 0.47, widthMul: 1.04, lengthMul: 1.02, style: "riviere" },
    description: "Graduated brilliant-cut diamonds with a suspended 3-carat pear teardrop solitaire in platinum."
  },
  {
    id: "necklace-sapphire-pendant",
    name: "Cannes Sapphire Geometry Pendant",
    category: "necklace",
    type: "necklace",
    image: "/ornaments/necklace-sapphire-pendant.png",
    metal: "18K White Gold",
    gems: "Cornflower Blue Sapphire & Diamonds",
    price: "₹4,60,000",
    materialPreset: "platinum",
    defaultScale: 1.20,
    defaultOffsetY: 0,
    fitProfile: { anchorBlend: 0.49, widthMul: 1.03, lengthMul: 1.0, style: "pendant" },
    description: "Architectural interlocking diamond frames centering a vivid royal blue sapphire on a sleek chain."
  },
  {
    id: "earrings-gold-jhumka",
    name: "Mayuri Gold Jhumkas",
    category: "earrings",
    type: "earrings",
    image: "/ornaments/earrings-gold-jhumka.svg",
    metal: "22K Gold",
    gems: "Ruby Stud & Seed Pearls",
    price: "₹1,75,000",
    materialPreset: "gold22k",
    defaultScale: 0.38,
    defaultOffsetY: 12,
    description: "Articulated bell-shaped earrings with swaying seed pearls and floral ruby tops."
  },
  {
    id: "earrings-diamond-drop",
    name: "Celeste Chandelier Drops",
    category: "earrings",
    type: "earrings",
    image: "/ornaments/earrings-diamond-drop.svg",
    metal: "18K White Gold",
    gems: "Brilliant White Diamonds",
    price: "₹4,90,000",
    materialPreset: "diamond",
    defaultScale: 0.35,
    defaultOffsetY: 10,
    description: "Triple-tier chandelier earrings cascading with marquise and pear-cut diamonds."
  },
  {
    id: "earrings-ruby-stud",
    name: "Crimson Halo Studs",
    category: "earrings",
    type: "earrings",
    image: "/ornaments/earrings-ruby-stud.svg",
    metal: "18K Yellow Gold",
    gems: "Pigeon Blood Rubies",
    price: "₹1,45,000",
    materialPreset: "ruby",
    defaultScale: 0.28,
    defaultOffsetY: 5,
    description: "Classic cushion-cut rubies encased within a radiant halo of pavé diamonds."
  },
  {
    id: "set-diamond-gala",
    name: "Cannes Red Carpet Suite",
    category: "set",
    type: "set",
    image: "/ornaments/necklace-diamond-solitaire.png",
    metal: "950 Platinum",
    gems: "Flawless Solitaire Diamonds",
    price: "₹14,70,000",
    materialPreset: "diamond",
    necklaceId: "necklace-diamond-solitaire",
    earringsId: "earrings-diamond-drop",
    description: "Breathtaking high-jewellery suite pairing the Rivière necklace with Celeste chandelier drops."
  },
  {
    id: "set-royal-heritage",
    name: "Royal Heritage 22K Bridal Suite",
    category: "set",
    type: "set",
    image: "/ornaments/necklace-royal-gold.png",
    metal: "22K Antique Gold",
    gems: "Rubies, Emeralds & Pearls",
    price: "₹5,60,000",
    materialPreset: "gold22k",
    necklaceId: "necklace-royal-gold",
    earringsId: "earrings-gold-jhumka",
    description: "Complete royal bridal ensemble featuring the 22K Heritage Choker and matching Mayuri Jhumkas."
  }
];
